// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eifwbemlfgqgiszxyixp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpZndiZW1sZmdxZ2lzenh5aXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODI2MDMsImV4cCI6MjA3MjU1ODYwM30.Y-qGBJ3rX68YbBUC6ARIaTXVUG3tnGIs7eejEe6c5fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});